version: "3.7"

x-service-base: &service-base
  image: aws_role_template
  build:
    context: ./
  volumes:
    - .:/usr/app

x-dev-base: &dev-base
  <<: *service-base
  image:  aws_role_template_dev
  build:
    context: ./
    dockerfile: Dockerfile-dev

services:
  make_template:
    <<: *service-base

  upload:
    <<: *service-base
    entrypoint: python generator/upload.py
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - .:/usr/app
      - ~/.aws/:/root/.aws:ro

  shell:
    <<: *service-base
    command: bash

  flake8:
    <<: *dev-base
    entrypoint: ["flake8", "--config", "generator/.flake8", "generator"]

  mypy:
    <<: *dev-base
    entrypoint: ["mypy", "generator"]

  safety:
    <<: *dev-base
    entrypoint: ["safety", "check"]

  # FIXME: ths really should use a python 3.7 image
  flake8-src:
    <<: *dev-base
    entrypoint: ["flake8", "--config", "src/python/.flake8", "src/python"]

  # FIXME: ths really should use a python 3.7 image
  mypy-src:
    <<: *dev-base
    entrypoint: ["mypy", "src/python"]

  dev-shell:
    <<: *dev-base
    command: bash
