FROM aws_role_template

COPY ./generator/dev-requirements.in .

RUN pip-compile --allow-unsafe --generate-hashes dev-requirements.in \
  --output-file dev-requirements.txt

RUN pip install --no-input --no-cache-dir -r dev-requirements.txt \
  -r dev-requirements.txt

ENTRYPOINT ["flake8", "--config", "generator/.flake8", "generator"]
